version: '3'
services:
    jupyter:
        image: joshuacook/jupyter
        ports:
            - 80:8888
        volumes:
            - .:/home/jovyan
        command: start-notebook.sh --NotebookApp.token="dtreesforthewin"
    postgis:
        image: joshuacook/postgis
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
